# Generated by Django 5.2.8 on 2025-12-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
