# Generated by Django 5.2.8 on 2025-12-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0004_searchlog_chunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
