# Generated by Django 5.2.8 on 2026-01-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0005_document_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='last_indexed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
