# Generated by Django 5.2.8 on 2026-01-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0006_document_last_indexed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='chunk_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of chunks created during last indexing'),
        ),
        migrations.AddField(
            model_name='document',
            name='embedding_model',
            field=models.CharField(blank=True, help_text='Embedding model used during last indexing', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='token_count',
            field=models.PositiveIntegerField(default=0, help_text='Approximate token count used for embeddings'),
        ),
    ]
